  [[main]]
  name = "News"
  identifier = "news"
  weight = 400
  url = "/"

  [[main]]
  name = "About me"
  weight = 100
  identifier = "about_me"
  url = "/about_me/"

  [[main]]
  name = "Research"
  weight = 200
  identifier = "research"
  url = "/research/"

  [[main]]
  name = "Publications"
  weight = 300
  identifier = "publications"
  url = "/publications/"

#  [[main]]
#  name = "News"
#  weight = 500
#  identifier = "news"
#  url = "/news/"
  
  [[main]]
  name = "Contact"
  weight = 500
  identifier = "contact"
  url = "/contact/"

#  [[footer]]
#  name = "imprint"
#  weight = 1
#  identifier = "imprint"
#  url = "/imprint/"